import { Geist, Geist_Mono, Fjalla_One, Bebas_Neue } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const fjallaOne = Fjalla_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-fjalla-one',
  display: 'swap',
})

const bebasNeue = Bebas_Neue({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-bebas-neue',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

<html lang="en"></html>

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className= {` ${geistSans.variable} ${geistMono.variable} ${fjallaOne.variable} ${bebasNeue.variable} antialiased` } style={{backgroundImage: "linear-gradient(to right, #393E46 0%, #393E46 73%, #333422 100%)",}} >
        {children}
      </body>
    </html>
  );
}
